# Generated by Django 3.0.2 on 2020-03-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicvine_id', models.IntegerField(unique=True)),
                ('comicvine_url', models.URLField(max_length=1000)),
                ('comicvine_matched', models.BooleanField(default=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('aliases', models.TextField()),
                ('short_description', models.TextField()),
                ('html_description', models.TextField()),
                ('thumb_url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
