# Generated by Django 3.0.2 on 2020-01-20 00:39

from django.db import migrations, models
import read_comics.users.models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unicorn'), ('O', 'Other')], default='U', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=utils.fields.ThumbnailImageField(null=True, upload_to=read_comics.users.models.get_user_image_name),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full Name'),
        ),
    ]
