# Generated by Django 3.0.2 on 2020-01-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200126_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
    ]
