# Generated by Django 3.0.2 on 2020-01-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_show_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(null=True, verbose_name='Last active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Show email in profile'),
        ),
    ]
