# Generated by Django 3.0.2 on 2020-02-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200127_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_image',
            new_name='_user_image',
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full name'),
        ),
    ]
